version: "1.0"
info:
  model: int-scaffold
packages:
- name: PLTAIPOCProject
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
- name: ShopifyDrinkItems
  version: "1.0"
  gitServerName: DacherCustomerRepo
  gitUrl: https://github.com/Bharath-Meka-0058MR744
  gitUsername: Bharath-Meka-0058MR744
  gitBranch: main
services:
- serviceName: project.pltaipoc.integrations:es_updatePOS
  packages:
  - name: PLTAIPOCProject
    version: "1.0"
  - name: WmShopifyProvider
    version: 10.7.0.0.16
  - name: SalesforceCRMUpdate
    version: "1.0"
  - name: ShopifyDrinkItems
    version: "1.0"
  - name: updatePOSRepo
    version: "1.0"
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.187
- serviceName: ShopifyDrinkItems:applyDiscountOnDrinks
  packages:
  - name: ShopifyDrinkItems
    version: "1.0"
  - name: WmShopifyProvider
    version: 10.7.0.0.16
- serviceName: pub.client:http
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.json:jsonStringToDocument
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: pub.globalVariable:getGlobalVariable
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
- serviceName: ShopifyDrinkItems:createPriceRule
  packages:
  - name: ShopifyDrinkItems
    version: "1.0"
  - name: WmShopifyProvider
    version: 10.7.0.0.16
- serviceName: ShopifyDrinkItems:generateDiscountCode
  packages:
  - name: ShopifyDrinkItems
    version: "1.0"
  - name: WmShopifyProvider
    version: 10.7.0.0.16
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.1
configurationVariables:
  jdbc.jdbcTestPool.waitingThread: "0"
  jdbc.jdbcTestPool.minConns: "0"
  jdbc.jdbcTestPool.snoopenabled: "false"
  jdbc.jdbcTestPool.expireTime: "60000"
  jdbc.jdbcTestPool.snoopparms: ddtdbg.ProtocolTraceEnable=true;ddtdbg.ProtocolTraceMaxline=16;ddtdbg.ProtocolTraceLocation=logs/snoop/jdbcTestPool.log;ddtdbg.ProtocolTraceShowTime=true
  jdbc.jdbcTestPool.password: "{AES}er+I3U8nDVm8F4DBRST1+A=="
  jdbc.jdbcTestPool.spyparms: SpyAttributes=(log=(file)logs/spy/jdbcTestPool.log;logTName=yes;timestamp=yes)
  jdbc.jdbcTestPool.dbURL: jdbc:mysql://mysql.test.local:3306/webm
  jdbc.jdbcTestPool.poolThreshold: "0"
  jdbc.jdbcTestPool.maxConns: "10"
  jdbc.jdbcTestPool.userid: root
  jdbc.jdbcTestPool.driverAlias: MySQL Database Java Connector Driver
  jdbc.jdbcTestPool.useSSL: "false"
  jdbc.jdbcTestPool.spyenabled: "false"
